language: python

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - sourceline: 'ppa:nicolasbock/qmmd'
        packages:
            - cmake
            - cmake-data
            - g++-6
            - gcc-6
            - gfortran-6
            - libblas-dev
            - libbml-dev
            - liblapack-dev
            - libmetis-dev
            - libopenmpi-dev
            - python
            - python3-numpy
            - python-numpy

env:
    - CC=gcc-6 FC=gfortran-6 CXX=g++-6 PROGRESS_GRAPHLIB=no  OMP_NUM_THREADS=4 COMMAND=testing

script:
    - >
        CMAKE_BUILD_TYPE=Debug
        PROGRESS_EXAMPLES=yes
        PROGRESS_OPENMP=yes
        PROGRESS_TESTING=yes
        VERBOSE_MAKEFILE=yes
        ./build.sh ${COMMAND}
    - pushd examples/gpmd
    - ./run_test.sh
    - popd
    - pushd examples/gpmdcov
    - OMP_NUM_THREADS=2 ./run.sh 2
    - popd

after_success:
  - bash <(curl -s https://codecov.io/bash) -v -X gcov
  - codecov --gcov-exec gcov-6
